services:
  pawpaw-api:
    container_name: pawpaw-api
    image: "leejongsuu1/pawpaw-api:latest"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  nginx:
    image: "nginx:1.15-alpine"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - pawpaw-api
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  redis:
    container_name: pawpaw-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"